[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "gcc"]

[phases.install]
cmds = ["python3 -m ensurepip", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn core.wsgi:application --log-file -"
