web: python3 -m gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
worker: python3 -m celery -A core worker --loglevel=info
beat: python3 -m celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler