[build]
builder = "nixpacks"
buildCommand = "python3 -m pip install -r requirements.txt && python3 manage.py collectstatic --noinput"

[deploy]
startCommand = "python3 -m gunicorn core.wsgi:application --log-file -"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
