[build]
builder = "DOCKERFILE"
dockerfilePath = "../Dockerfile"

[deploy]
startCommand = "gunicorn core.wsgi:application --log-file -"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
